export const GalleryData =[
    {
        id:1,
        title:"Graduation",
        image:"./images/p1.jpg",
        
    },
    {
        id:2,
        title:"car",
        image:"./images/p2.jpg"
    },
    {
        id:3,
        title:"car",
        image:"./images/p3.jpg"
    },
    {
        id:4,
        title:"car",
        image:"./images/p4.jpg"
    },
    {
        id:5,
        title:"car",
        image:"./images/p5.jpg"
    },
    {
        id:6,
        title:"car",
        image:"./images/p6.jpg"
    },
    {
        id:7,
        title:"car",
        image:"./images/p9.jpg"
    },
    {
        id:8,
        title:"bike",
        image:"./images/p11.jpg"
    },
]
